# Generated by Django 4.2.5 on 2024-04-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FA_overview", "0006_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="facebook_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="homepage_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="instagram_link",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin_link",
        ),
    ]
